### ISSUE TITLE
Provide a mechanism for users to re-authorize after complete token invalidation

### ISSUE THREAD

**Issue by carwin** [carwin/snlack#16]
## Abstract
If the Snyk App's authorization/access and refresh keys are both expired, the only thing to do is re-authorize. This state needs to be tracked by some means and the user needs to be notified and prompted to re-authorize.

## Tasks
- [ ] Refactor the current condition which decides whether to show the user a config form or the "Auth with Snyk" button on the App Home view. Tie the view switching to a boolean value set on the user's db entry instead, defaulted to false.
- [ ] When the application encounters a totally expired set of credentials, set the flag in the user's db entry back to false.[^1]
- [ ] When the application encounters a totally expired set of credentials, respond to the user in whichever channel they initiated their last command from, letting them know credentials / authorization have expired and direct them to the App Home view to re-auth.

[^1]: Is a 400 status from the axios response interceptor a good enough trigger for this? I assume so, but perhaps there's still a way to salvage an existing authorization from there.
