### ISSUE TITLE
Implement slash command for listing project dependencies

### ISSUE THREAD

**Issue by carwin** [carwin/snlack#2]
## Abstract
Users should be able to request a list of dependencies for a given project. Because this list could easily exceed Slack's message limits, the first, most basic, version of this should simply be a truncated list with a link to view the entire dependency tree on Snyk.io.
Future enhancements might include creating and presenting a Dep Graph or even providing an SBOM in SPDX or CycloneDX format.

## Tasks
- [x] `/snyk project <Project Name> dependencies`
- [ ] `/snyk project <Project Name> <Org Name> dependencies`[^1]
- [x] `/snyk project <Project ID> dependencies` [^2]

[^1]: The explicit form of the command, `/snyk project <Project Name> <Org Name> dependencies`, should be suggested to the user if the first form is used and more than one project is found (e.g. in multiple Orgs).
[^2]: We should also allow using Project ID instead of the Project's name, though it seems unlikely users will have that information at hand. It will be easier to for implementing buttons elsewhere in the app, like on the project list or individual project view.

**Comment by carwin** [comment]
Changing my mind about this one - I think it makes more sense to have the variable bits of the command at the end. Also, if we're looking at dependencies, I think it's inferred that we're looking at a project's dependencies, so the revised command list should probably look more like:

- [ ] `/snyk dependencies <Project Name>`
- [ ] `/snyk dependencies <Project ID>`
- [ ] `/snyk dependencies <Project Name> <Org Name>`
- [ ] `/snyk dependencies <Project ID> <Org Name>`
- [ ] `/snyk dependencies <Project Name> <Org ID>`
- [ ] `/snyk dependencies <Project ID> <Org ID>`

As a convenience it might even be nice to shorten `/snyk dependencies` to just `/snyk deps` or perhaps even add a completely second `/dependencies` command in the future.

**Comment by carwin** [comment]
Since having the same project tracked in multiple Snyk orgs seems like an edge case, I'm going to pull that bit of this task out into its own as a backlog item.
