### ISSUE TITLE
Implement slash command(s) for interacting with Snyk projects

### ISSUE THREAD

**Issue by carwin** [carwin/snlack#4]
## Abstract
Users should be able to retrieve a list of all of their projects as well as a list of projects within a specific Snyk Organization.

## Tasks
- [x] `/snyk project`[^1]
- [x] `/snyk project help`[^2]
- [x] `/snyk project list`[^3]
- [x] `/snyk project list <Org Name>`
- [x] `/snyk project list <Org ID>`

[^1]: Point to the help command
[^2]: Describe project related commands
[^3]: Lists all projects, truncated by necessity - Slack won't support a list that's too long or contains too many Block Kit blocks.
